# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go - Deploy WASM static files

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build WASM static pages
      run: |
         ./build_wasm
      shell: bash

    - name: Commit and push WASM static pages
      env:
        CI_COMMIT_MESSAGE: Add WASM static pages - $(date +'%Y-%m-%dT%H:%M:%S')
        CI_COMMIT_AUTHOR: padaiyal
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "user@gpt.padaiyal.com"
        git add --force *.wasm *.html wasm_exec.js
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
