# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go WASM - Build, Test & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/go_wasm_build_test.yml
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Commit and push WASM static pages
      if: github.event_name == 'push'
      env:
        CI_COMMIT_MESSAGE: Add WASM static pages - $(date +'%Y-%m-%dT%H:%M:%S')
        CI_COMMIT_AUTHOR: padaiyal
      run: |
        git status
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add --force script/*.wasm
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push